version: "3.8"

services:
  sqlserver:
    image: mysql:8.3
    container_name: sqlserver
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mais-portal-network

  user_management_portal:
    image: alpine
    container_name: user_management_portal
    command: ["sleep", "infinity"]
    networks:
      - mais-portal-network

volumes:
  mysql_data:

networks:
  mais-portal-network:
    driver: bridge
