version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-lts
    container_name: sqlserver
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Passw0rd"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - plus-portal-network

  php:
    image: php:8.2-cli
    container_name: php
    volumes:
      - ../laravel:/var/www/html
    working_dir: /var/www/html
    networks:
      - plus-portal-network
    command: ["sleep", "infinity"]

volumes:
  sqlserver_data:

networks:
  plus-portal-network:
    driver: bridge
